### ISSUE TITLE
"Adding the library to your project" not working

### ISSUE THREAD

**Issue by brunomacf** [aerogear/aerogear-ios-http#23]
I've tried add aerogear through CocoaPods and drawing it to my project and none of them are working! I'm using CocoaPods Beta release and it could not find AeroGearHttp module. In the case of drag the file, i think some linking is missing in your Readme tutorial, because Http class can't be found.

**Comment by cvasilak** [comment]
Hi @brunomacf thanks for giving it a spin. Have updated the steps to be more precise in PR https://github.com/aerogear/aerogear-ios-http/pull/25

let us know if it works for you. Thanks!
